/**
 * WatermelonDB Schema for Monyvi
 * AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Run 'npm run db:sync' to regenerate
 */

import { appSchema, tableSchema } from "@nozbe/watermelondb";

import { SMS_REVIEW_DRAFT_TABLES } from "./local-schema/sms-review-draft-schema";

export const schema = appSchema({
  version: 26,
  tables: [
    tableSchema({
      name: "account_sms_senders",
      columns: [
        { name: "account_id", type: "string", isIndexed: true },
        { name: "created_at", type: "number" },
        { name: "deleted", type: "boolean" },
        { name: "normalized_sender_name", type: "string" },
        { name: "sender_name", type: "string" },
        { name: "updated_at", type: "number" },
      ],
    }),

    tableSchema({
      name: "accounts",
      columns: [
        { name: "balance", type: "number" },
        { name: "created_at", type: "number" },
        { name: "currency", type: "string" },
        { name: "deleted", type: "boolean" },
        {
          name: "institution_id",
          type: "string",
          isOptional: true,
          isIndexed: true,
        },
        { name: "is_default", type: "boolean" },
        { name: "name", type: "string" },
        { name: "provider_display_name", type: "string", isOptional: true },
        { name: "type", type: "string" },
        { name: "updated_at", type: "number" },
        { name: "user_id", type: "string", isIndexed: true },
      ],
    }),

    tableSchema({
      name: "asset_metals",
      columns: [
        { name: "asset_id", type: "string", isIndexed: true },
        { name: "created_at", type: "number" },
        { name: "deleted", type: "boolean" },
        { name: "item_form", type: "string", isOptional: true },
        { name: "metal_type", type: "string" },
        { name: "purity_fraction", type: "number" },
        { name: "updated_at", type: "number" },
        { name: "weight_grams", type: "number" },
      ],
    }),

    tableSchema({
      name: "assets",
      columns: [
        { name: "created_at", type: "number" },
        { name: "currency", type: "string" },
        { name: "deleted", type: "boolean" },
        { name: "is_liquid", type: "boolean" },
        { name: "name", type: "string" },
        { name: "notes", type: "string", isOptional: true },
        { name: "purchase_date", type: "number" },
        { name: "purchase_price", type: "number" },
        { name: "type", type: "string" },
        { name: "updated_at", type: "number" },
        { name: "user_id", type: "string", isIndexed: true },
      ],
    }),

    tableSchema({
      name: "bank_details",
      columns: [
        { name: "account_id", type: "string", isIndexed: true },
        { name: "account_number", type: "string", isOptional: true },
        { name: "card_last_4", type: "number", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "deleted", type: "boolean" },
        { name: "updated_at", type: "number" },
      ],
    }),

    tableSchema({
      name: "budgets",
      columns: [
        { name: "alert_fired_level", type: "string", isOptional: true },
        { name: "alert_threshold", type: "number" },
        { name: "amount", type: "number" },
        {
          name: "category_id",
          type: "string",
          isOptional: true,
          isIndexed: true,
        },
        { name: "created_at", type: "number" },
        { name: "currency", type: "string", isOptional: true },
        { name: "deleted", type: "boolean" },
        { name: "name", type: "string" },
        { name: "pause_intervals", type: "string" },
        { name: "paused_at", type: "string", isOptional: true },
        { name: "period", type: "string" },
        { name: "period_end", type: "number", isOptional: true },
        { name: "period_start", type: "number", isOptional: true },
        { name: "status", type: "string" },
        { name: "type", type: "string" },
        { name: "updated_at", type: "number" },
        { name: "user_id", type: "string", isIndexed: true },
      ],
    }),

    tableSchema({
      name: "categories",
      columns: [
        { name: "color", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "deleted", type: "boolean" },
        { name: "display_name", type: "string" },
        { name: "icon", type: "string" },
        { name: "icon_library", type: "string" },
        { name: "is_hidden", type: "boolean" },
        { name: "is_internal", type: "boolean" },
        { name: "is_system", type: "boolean" },
        { name: "level", type: "number" },
        { name: "nature", type: "string", isOptional: true },
        {
          name: "parent_id",
          type: "string",
          isOptional: true,
          isIndexed: true,
        },
        { name: "sort_order", type: "number", isOptional: true },
        { name: "system_name", type: "string" },
        { name: "type", type: "string", isOptional: true },
        { name: "updated_at", type: "number" },
        { name: "usage_count", type: "number" },
        { name: "user_id", type: "string", isOptional: true, isIndexed: true },
      ],
    }),

    tableSchema({
      name: "daily_snapshot_assets",
      columns: [
        { name: "created_at", type: "number" },
        { name: "snapshot_date", type: "number" },
        { name: "total_assets_usd", type: "number" },
        { name: "user_id", type: "string", isIndexed: true },
      ],
    }),

    tableSchema({
      name: "daily_snapshot_balance",
      columns: [
        { name: "created_at", type: "number" },
        { name: "snapshot_date", type: "number" },
        { name: "total_accounts_usd", type: "number" },
        { name: "user_id", type: "string", isIndexed: true },
      ],
    }),

    tableSchema({
      name: "daily_snapshot_net_worth",
      columns: [
        { name: "created_at", type: "number" },
        { name: "snapshot_date", type: "number" },
        { name: "total_accounts", type: "number" },
        { name: "total_assets", type: "number" },
        { name: "total_net_worth", type: "number" },
        { name: "user_id", type: "string", isIndexed: true },
      ],
    }),

    tableSchema({
      name: "debts",
      columns: [
        { name: "account_id", type: "string", isIndexed: true },
        { name: "created_at", type: "number" },
        { name: "date", type: "number" },
        { name: "deleted", type: "boolean" },
        { name: "due_date", type: "number", isOptional: true },
        { name: "notes", type: "string", isOptional: true },
        { name: "original_amount", type: "number" },
        { name: "outstanding_amount", type: "number" },
        { name: "party_name", type: "string" },
        { name: "status", type: "string" },
        { name: "type", type: "string" },
        { name: "updated_at", type: "number" },
        { name: "user_id", type: "string", isIndexed: true },
      ],
    }),

    tableSchema({
      name: "financial_action_groups",
      columns: [
        { name: "action_id", type: "string", isIndexed: true },
        { name: "created_at", type: "number" },
        { name: "deleted", type: "boolean" },
        { name: "domain", type: "string" },
        { name: "domain_reference_id", type: "string", isIndexed: true },
        { name: "expected_account_revision", type: "string", isOptional: true },
        { name: "kind", type: "string" },
        { name: "outcome_json", type: "string", isOptional: true },
        { name: "payload_hash", type: "string" },
        { name: "payload_json", type: "string" },
        { name: "rejection_code", type: "string", isOptional: true },
        { name: "server_outcome", type: "string", isOptional: true },
        { name: "state", type: "string" },
        { name: "updated_at", type: "number" },
        { name: "user_id", type: "string", isIndexed: true },
      ],
    }),

    tableSchema({
      name: "market_rates",
      columns: [
        { name: "aed_usd", type: "number" },
        { name: "aud_usd", type: "number" },
        { name: "bhd_usd", type: "number" },
        { name: "btc_usd", type: "number" },
        { name: "cad_usd", type: "number" },
        { name: "chf_usd", type: "number" },
        { name: "cny_usd", type: "number" },
        { name: "created_at", type: "number" },
        { name: "dkk_usd", type: "number" },
        { name: "dzd_usd", type: "number" },
        { name: "egp_usd", type: "number" },
        { name: "eur_usd", type: "number" },
        { name: "gbp_usd", type: "number" },
        { name: "gold_usd_per_gram", type: "number" },
        { name: "hkd_usd", type: "number" },
        { name: "inr_usd", type: "number" },
        { name: "iqd_usd", type: "number" },
        { name: "isk_usd", type: "number" },
        { name: "jod_usd", type: "number" },
        { name: "jpy_usd", type: "number" },
        { name: "kpw_usd", type: "number" },
        { name: "krw_usd", type: "number" },
        { name: "kwd_usd", type: "number" },
        { name: "lyd_usd", type: "number" },
        { name: "mad_usd", type: "number" },
        { name: "myr_usd", type: "number" },
        { name: "nok_usd", type: "number" },
        { name: "nzd_usd", type: "number" },
        { name: "omr_usd", type: "number" },
        { name: "palladium_usd_per_gram", type: "number" },
        { name: "platinum_usd_per_gram", type: "number" },
        { name: "qar_usd", type: "number" },
        { name: "rub_usd", type: "number" },
        { name: "sar_usd", type: "number" },
        { name: "sek_usd", type: "number" },
        { name: "sgd_usd", type: "number" },
        { name: "silver_usd_per_gram", type: "number" },
        { name: "timestamp_currency", type: "string", isOptional: true },
        { name: "timestamp_metal", type: "string", isOptional: true },
        { name: "tnd_usd", type: "number" },
        { name: "try_usd", type: "number" },
        { name: "updated_at", type: "number" },
        { name: "zar_usd", type: "number" },
      ],
    }),

    tableSchema({
      name: "profiles",
      columns: [
        { name: "ai_processing_consent", type: "string", isOptional: true },
        { name: "avatar_url", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "deleted", type: "boolean" },
        { name: "display_name", type: "string", isOptional: true },
        { name: "first_name", type: "string", isOptional: true },
        { name: "last_name", type: "string", isOptional: true },
        { name: "notification_settings", type: "string", isOptional: true },
        { name: "onboarding_completed", type: "boolean" },
        { name: "onboarding_flags", type: "string", isOptional: true },
        { name: "preferred_currency", type: "string" },
        { name: "preferred_language", type: "string" },
        { name: "setup_guide_completed", type: "boolean" },
        { name: "sms_detection_enabled", type: "boolean" },
        { name: "theme", type: "string" },
        { name: "updated_at", type: "number" },
        { name: "user_id", type: "string", isIndexed: true },
      ],
    }),

    tableSchema({
      name: "recurring_payments",
      columns: [
        { name: "account_id", type: "string", isIndexed: true },
        { name: "action", type: "string" },
        { name: "amount", type: "number" },
        { name: "category_id", type: "string", isIndexed: true },
        { name: "created_at", type: "number" },
        { name: "currency", type: "string" },
        { name: "deleted", type: "boolean" },
        { name: "end_date", type: "number", isOptional: true },
        { name: "frequency", type: "string" },
        { name: "frequency_value", type: "number", isOptional: true },
        {
          name: "linked_debt_id",
          type: "string",
          isOptional: true,
          isIndexed: true,
        },
        { name: "name", type: "string" },
        { name: "next_due_date", type: "number" },
        { name: "notes", type: "string", isOptional: true },
        { name: "start_date", type: "number" },
        { name: "status", type: "string" },
        { name: "type", type: "string" },
        { name: "updated_at", type: "number" },
        { name: "user_id", type: "string", isIndexed: true },
      ],
    }),

    tableSchema({
      name: "sms_ai_negative_outcomes",
      columns: [
        { name: "created_at", type: "number" },
        { name: "deleted", type: "boolean" },
        { name: "is_terminal", type: "boolean" },
        { name: "last_classified_at", type: "string" },
        { name: "original_received_at", type: "string" },
        { name: "sms_fingerprint", type: "string", isIndexed: true },
        { name: "strike_count", type: "number" },
        { name: "terminal_at", type: "string", isOptional: true },
        { name: "updated_at", type: "number" },
        { name: "user_id", type: "string", isIndexed: true },
      ],
    }),

    tableSchema({
      name: "transactions",
      columns: [
        { name: "account_id", type: "string", isIndexed: true },
        { name: "amount", type: "number" },
        { name: "category_id", type: "string", isIndexed: true },
        { name: "counterparty", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "currency", type: "string" },
        { name: "date", type: "number" },
        { name: "deleted", type: "boolean" },
        { name: "is_draft", type: "boolean" },
        {
          name: "linked_asset_id",
          type: "string",
          isOptional: true,
          isIndexed: true,
        },
        {
          name: "linked_debt_id",
          type: "string",
          isOptional: true,
          isIndexed: true,
        },
        {
          name: "linked_recurring_id",
          type: "string",
          isOptional: true,
          isIndexed: true,
        },
        { name: "note", type: "string", isOptional: true },
        {
          name: "sms_fingerprint",
          type: "string",
          isOptional: true,
          isIndexed: true,
        },
        { name: "source", type: "string" },
        { name: "type", type: "string" },
        { name: "updated_at", type: "number" },
        { name: "user_id", type: "string", isIndexed: true },
      ],
    }),

    tableSchema({
      name: "transfers",
      columns: [
        { name: "amount", type: "number" },
        { name: "converted_amount", type: "number", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "currency", type: "string" },
        { name: "date", type: "number" },
        { name: "deleted", type: "boolean" },
        { name: "exchange_rate", type: "number", isOptional: true },
        { name: "from_account_id", type: "string", isIndexed: true },
        { name: "notes", type: "string", isOptional: true },
        {
          name: "sms_fingerprint",
          type: "string",
          isOptional: true,
          isIndexed: true,
        },
        { name: "to_account_id", type: "string", isIndexed: true },
        { name: "updated_at", type: "number" },
        { name: "user_id", type: "string", isIndexed: true },
      ],
    }),

    tableSchema({
      name: "user_category_settings",
      columns: [
        { name: "category_id", type: "string", isIndexed: true },
        { name: "created_at", type: "number" },
        { name: "deleted", type: "boolean" },
        { name: "is_hidden", type: "boolean" },
        { name: "nature", type: "string", isOptional: true },
        { name: "updated_at", type: "number" },
        { name: "user_id", type: "string", isIndexed: true },
      ],
    }),
    ...SMS_REVIEW_DRAFT_TABLES,
  ],
});
