import type { TrustedSmsPattern } from "../trusted-sms-pattern-types";

export const QNB_EGYPT_TRUSTED_SMS_PATTERNS_02 = [
  {
    schemaVersion: 1,
    patternId: "qnb-alahli-otp-bebasata-v1",
    patternVersion: 1,
    catalogVersion: 1,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB ALAHLI"],
    messageFamily: "otp",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-alahli-otp-bebasata-v1",
    segments: [
      {
        kind: "fixed",
        text: "QNB Bebasata onetime password: ",
      },
      {
        kind: "placeholder",
        token: "REFERENCE",
        semanticRole: "otp_code",
      },
      {
        kind: "fixed",
        text: " , إدخل هذا الرقم بنفسك ولا تفصح عنه لأي شخص",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "otp",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "236cb60a491ff737c063da9c624e9b3bdb2ad16f0dae0c342f353d43ccd3080f",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-alahli-informational-card-fee-refund-ar-v1",
    patternVersion: 1,
    catalogVersion: 1,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB ALAHLI"],
    messageFamily: "informational",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-alahli-informational-card-fee-refund-ar-v1",
    segments: [
      {
        kind: "fixed",
        text: "عميلنا العزيز ,من اليوم وحتي نهاية السنة سيتم رد مصاريف اصدار بطاقة QNBالأهلي الائتمانية الأساسية والتابعة مع اول استخدام تطبق الشروط ",
      },
      {
        kind: "placeholder",
        token: "URL",
        semanticRole: "public_url",
      },
      {
        kind: "fixed",
        text: " ت.ض ",
      },
      {
        kind: "placeholder",
        token: "REFERENCE",
        semanticRole: "public_reference",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "informational",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "99a215b0d9769c0545a5c6b454b974aec2c60db21b05d4093f1cd878b899a2f9",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-alahli-informational-foreign-currency-ar-v1",
    patternVersion: 1,
    catalogVersion: 1,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB ALAHLI"],
    messageFamily: "informational",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-alahli-informational-foreign-currency-ar-v1",
    segments: [
      {
        kind: "fixed",
        text: "عميلنا العزيز، برجاء العلم ان معاملات الدفع بالعملات الأجنبية محلياً او دولياً على بطاقات الخصم المباشر المصدرة على حساباتكم بالجنيه المصري متوقفة حالياً، ويتم استخدام البطاقة بالجنيه المصري فقط تطبق الشروط ت ض ",
      },
      {
        kind: "placeholder",
        token: "REFERENCE",
        semanticRole: "public_reference",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "informational",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "748f531a97ebc5972df5432f8f4c851f4b9aa25fe5ef86d585bc4efc078f24e6",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-informational-fees-ar-v1",
    patternVersion: 1,
    catalogVersion: 1,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "informational",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-informational-fees-ar-v1",
    segments: [
      {
        kind: "fixed",
        text: "عميلنا العزيز، يرجي العلم بأنه تم تعديل المصاريف الخاصة بالخدمات والمنتجات المصرفية. لمزيد من المعلومات برجاء زيارة: ",
      },
      {
        kind: "placeholder",
        token: "URL",
        semanticRole: "public_url",
      },
      {
        kind: "fixed",
        text: " تطبق الشروط والاحكام ت.ض:",
      },
      {
        kind: "placeholder",
        token: "REFERENCE",
        semanticRole: "public_reference",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "informational",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "acca9e0976f9caf455a5b8fb2f6321b1cd05e1c60a54f6b74487a7acc4a91d7d",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-promotional-olympics-ar-v1",
    patternVersion: 1,
    catalogVersion: 1,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "promotional",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-promotional-olympics-ar-v1",
    segments: [
      {
        kind: "fixed",
        text: "اصدر، فعل واستخدم بطاقاتQNB Visa الائتمانية خلال فاعليات الألعاب الأولمبية باريس ",
      },
      {
        kind: "placeholder",
        token: "DATE",
        semanticRole: "campaign_year",
      },
      {
        kind: "fixed",
        text: " وأحصل على نقاط ولاء إضافية تصل الي ",
      },
      {
        kind: "placeholder",
        token: "AMOUNT",
        semanticRole: "promotional_amount",
      },
      {
        kind: "fixed",
        text: " نقطة لطلب بطاقة ائتمانية:",
      },
      {
        kind: "placeholder",
        token: "URL",
        semanticRole: "public_url",
      },
      {
        kind: "fixed",
        text: " للمزيد:",
      },
      {
        kind: "placeholder",
        token: "URL",
        semanticRole: "public_url",
      },
      {
        kind: "fixed",
        text: " تطبق الشروط ت ض ",
      },
      {
        kind: "placeholder",
        token: "REFERENCE",
        semanticRole: "public_reference",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "promotional",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "42c03b577b2cf6407166783dfc61e4569106c01b0ad0c6927ac9edce61346aea",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-card-purchase-usd-v1",
    patternVersion: 1,
    catalogVersion: 1,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "card_purchase",
    currency: "USD",
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-card-purchase-usd-v1",
    segments: [
      {
        kind: "fixed",
        text: "Your Debit Card **",
      },
      {
        kind: "placeholder",
        token: "LAST4",
        semanticRole: "card_last4",
      },
      {
        kind: "fixed",
        text: " had a Successful transaction of ",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "fixed",
        text: " ",
      },
      {
        kind: "placeholder",
        token: "AMOUNT",
        semanticRole: "transaction_amount",
      },
      {
        kind: "fixed",
        text: " @",
      },
      {
        kind: "placeholder",
        token: "MERCHANT",
        semanticRole: "merchant_name",
      },
      {
        kind: "fixed",
        text: ",your available bal.",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "fixed",
        text: " ",
      },
      {
        kind: "placeholder",
        token: "BALANCE",
        semanticRole: "available_balance",
      },
      {
        kind: "fixed",
        text: " for lost/stolen card call ",
      },
      {
        kind: "placeholder",
        token: "PHONE",
        semanticRole: "provider_hotline",
      },
    ],
    expectedOutcome: {
      kind: "transaction",
      direction: "expense",
      reviewStatus: "needs_review",
      reviewReasons: ["low_confidence"],
      confidenceCeiling: 0.8,
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "8d99457ab881d600b25b5467ef82f02e76e8a7a94356394fdebe6c474934d3de",
  },
] as const satisfies readonly TrustedSmsPattern[];
