import type { TrustedSmsPattern } from "../trusted-sms-pattern-types";

export const QNB_EGYPT_TRUSTED_SMS_PATTERNS_03 = [
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-card-purchase-usd-v1",
    patternVersion: 1,
    catalogVersion: 2,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "card_purchase",
    currency: "USD",
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-card-purchase-usd-v1",
    segments: [
      {
        kind: "fixed",
        text: "Your Debit Card **",
      },
      {
        kind: "placeholder",
        token: "LAST4",
        semanticRole: "card_last4",
      },
      {
        kind: "fixed",
        text: " had a Successful transaction of ",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "fixed",
        text: " ",
      },
      {
        kind: "placeholder",
        token: "AMOUNT",
        semanticRole: "transaction_amount",
      },
      {
        kind: "fixed",
        text: " @",
      },
      {
        kind: "placeholder",
        token: "MERCHANT",
        semanticRole: "merchant_name",
      },
      {
        kind: "fixed",
        text: ",your available bal.",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "placeholder",
        token: "BALANCE",
        semanticRole: "available_balance",
      },
      {
        kind: "fixed",
        text: " for lost/stolen card call ",
      },
      {
        kind: "placeholder",
        token: "PHONE",
        semanticRole: "provider_hotline",
      },
    ],
    expectedOutcome: {
      kind: "transaction",
      direction: "expense",
      reviewStatus: "needs_review",
      reviewReasons: ["low_confidence"],
      confidenceCeiling: 0.8,
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "b4119be9cac9767fd22f5f0783c024c0f0ec526bbda678bbabe290d23a036794",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-otp-card-purchase-v1",
    patternVersion: 1,
    catalogVersion: 2,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "otp",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-otp-card-purchase-v1",
    segments: [
      {
        kind: "fixed",
        text: "QNB OTP:",
      },
      {
        kind: "placeholder",
        token: "REFERENCE",
        semanticRole: "otp_code",
      },
      {
        kind: "fixed",
        text: " at ",
      },
      {
        kind: "placeholder",
        token: "MERCHANT",
        semanticRole: "merchant_name",
      },
      {
        kind: "fixed",
        text: " for ",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "fixed",
        text: " ",
      },
      {
        kind: "placeholder",
        token: "AMOUNT",
        semanticRole: "transaction_amount",
      },
      {
        kind: "fixed",
        text: " الرقم السرى مخصص لعملية الشراء اونلاين برجاء عدم الافصاح عنه",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "otp",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "3d90e46e7ebc0bb9eb43700e8e20a3c90926b98c9e8a0d5717feb013a71e0027",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-atm-card-egp-v1",
    patternVersion: 1,
    catalogVersion: 2,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "atm_withdrawal",
    currency: "EGP",
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-atm-card-egp-v1",
    segments: [
      {
        kind: "fixed",
        text: "Your Debit Card **",
      },
      {
        kind: "placeholder",
        token: "LAST4",
        semanticRole: "card_last4",
      },
      {
        kind: "fixed",
        text: " had a Successful transaction of ",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "fixed",
        text: " ",
      },
      {
        kind: "placeholder",
        token: "AMOUNT",
        semanticRole: "transaction_amount",
      },
      {
        kind: "fixed",
        text: " @",
      },
      {
        kind: "placeholder",
        token: "ATM_TERMINAL",
        semanticRole: "atm_terminal",
      },
      {
        kind: "fixed",
        text: ",your available bal.",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "placeholder",
        token: "BALANCE",
        semanticRole: "available_balance",
      },
      {
        kind: "fixed",
        text: " for lost/stolen card call ",
      },
      {
        kind: "placeholder",
        token: "PHONE",
        semanticRole: "provider_hotline",
      },
    ],
    expectedOutcome: {
      kind: "transaction",
      direction: "expense",
      reviewStatus: "needs_review",
      reviewReasons: ["low_confidence", "cash_transfer_review"],
      confidenceCeiling: 0.8,
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "f3ee8ae2d7fe02422611cc19b92dc15b3775e7c638891c1c4a678cb6acd45235",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-atm-account-egp-v1",
    patternVersion: 1,
    catalogVersion: 2,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "atm_withdrawal",
    currency: "EGP",
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-atm-account-egp-v1",
    segments: [
      {
        kind: "fixed",
        text: "Dear Client, Amount of ",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "placeholder",
        token: "AMOUNT",
        semanticRole: "transaction_amount",
      },
      {
        kind: "fixed",
        text: " was debited from your account for cash withdrawal based on your request. For more information, please call ",
      },
      {
        kind: "placeholder",
        token: "PHONE",
        semanticRole: "provider_hotline",
      },
    ],
    expectedOutcome: {
      kind: "transaction",
      direction: "expense",
      reviewStatus: "needs_review",
      reviewReasons: ["low_confidence", "cash_transfer_review"],
      confidenceCeiling: 0.8,
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "baa1835b305b5fdd67b98d05e1e3e35a541e8db38e006c9aaa7a6bed3bddcc4c",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-incoming-ipn-egp-v1",
    patternVersion: 1,
    catalogVersion: 2,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "incoming_ipn_transfer",
    currency: "EGP",
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-incoming-ipn-egp-v1",
    segments: [
      {
        kind: "fixed",
        text: "IPN transfer received with amount of ",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "fixed",
        text: " ",
      },
      {
        kind: "placeholder",
        token: "AMOUNT",
        semanticRole: "transaction_amount",
      },
      {
        kind: "fixed",
        text: " on ",
      },
      {
        kind: "placeholder",
        token: "ACCOUNT",
        semanticRole: "source_account_suffix",
      },
      {
        kind: "fixed",
        text: " on ",
      },
      {
        kind: "placeholder",
        token: "DATE",
        semanticRole: "transaction_date",
      },
      {
        kind: "fixed",
        text: " at ",
      },
      {
        kind: "placeholder",
        token: "TIME",
        semanticRole: "transaction_time",
      },
      {
        kind: "fixed",
        text: ". Ref# ",
      },
      {
        kind: "placeholder",
        token: "REFERENCE",
        semanticRole: "transaction_reference",
      },
      {
        kind: "fixed",
        text: ". For more details call ",
      },
      {
        kind: "placeholder",
        token: "PHONE",
        semanticRole: "provider_hotline",
      },
      {
        kind: "fixed",
        text: ".",
      },
    ],
    expectedOutcome: {
      kind: "transaction",
      direction: "income",
      reviewStatus: "needs_review",
      reviewReasons: ["low_confidence"],
      confidenceCeiling: 0.8,
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "48e429f0814ce2e09ec3aa723f507d2e35879a128d3829b4bb9174cd7ce658a5",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-outgoing-ipn-egp-v1",
    patternVersion: 1,
    catalogVersion: 2,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "outgoing_ipn_transfer",
    currency: "EGP",
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-outgoing-ipn-egp-v1",
    segments: [
      {
        kind: "fixed",
        text: "IPN transfer sent with amount of ",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "fixed",
        text: " ",
      },
      {
        kind: "placeholder",
        token: "AMOUNT",
        semanticRole: "transaction_amount",
      },
      {
        kind: "fixed",
        text: " from ",
      },
      {
        kind: "placeholder",
        token: "ACCOUNT",
        semanticRole: "source_account_suffix",
      },
      {
        kind: "fixed",
        text: " on ",
      },
      {
        kind: "placeholder",
        token: "DATE",
        semanticRole: "transaction_date",
      },
      {
        kind: "fixed",
        text: " at ",
      },
      {
        kind: "placeholder",
        token: "TIME",
        semanticRole: "transaction_time",
      },
      {
        kind: "fixed",
        text: ". Ref# ",
      },
      {
        kind: "placeholder",
        token: "REFERENCE",
        semanticRole: "transaction_reference",
      },
      {
        kind: "fixed",
        text: ". For more details call ",
      },
      {
        kind: "placeholder",
        token: "PHONE",
        semanticRole: "provider_hotline",
      },
      {
        kind: "fixed",
        text: ".",
      },
    ],
    expectedOutcome: {
      kind: "transaction",
      direction: "expense",
      reviewStatus: "needs_review",
      reviewReasons: ["low_confidence"],
      confidenceCeiling: 0.8,
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "128de0daf9c1eb2b7c15d3bb88eededd0a9415148c2b54125dcceca9937555b6",
  },
] as const satisfies readonly TrustedSmsPattern[];
