import type { TrustedSmsPattern } from "../trusted-sms-pattern-types";

export const QNB_EGYPT_TRUSTED_SMS_PATTERNS_01 = [
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-refund-card-egp-v1",
    patternVersion: 1,
    catalogVersion: 1,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "refund_or_reversal",
    currency: "EGP",
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-refund-card-egp-v1",
    segments: [
      {
        kind: "fixed",
        text: "Your transaction with Debit Card **",
      },
      {
        kind: "placeholder",
        token: "LAST4",
        semanticRole: "card_last4",
      },
      {
        kind: "fixed",
        text: " @",
      },
      {
        kind: "placeholder",
        token: "MERCHANT",
        semanticRole: "merchant_name",
      },
      {
        kind: "fixed",
        text: " with ",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "fixed",
        text: " ",
      },
      {
        kind: "placeholder",
        token: "AMOUNT",
        semanticRole: "transaction_amount",
      },
      {
        kind: "fixed",
        text: " has been reversed",
      },
    ],
    expectedOutcome: {
      kind: "transaction",
      direction: "income",
      reviewStatus: "needs_review",
      reviewReasons: ["low_confidence"],
      confidenceCeiling: 0.8,
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "18b20ffcb5f4c58b28cdf23c645f3ae5de0c49198fc6a470ebd9b3690b6cc532",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-refund-ipn-egp-v1",
    patternVersion: 1,
    catalogVersion: 1,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "refund_or_reversal",
    currency: "EGP",
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-refund-ipn-egp-v1",
    segments: [
      {
        kind: "fixed",
        text: "IPN transfer debited from ",
      },
      {
        kind: "placeholder",
        token: "ACCOUNT",
        semanticRole: "source_account_suffix",
      },
      {
        kind: "fixed",
        text: " with amount ",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "fixed",
        text: " ",
      },
      {
        kind: "placeholder",
        token: "AMOUNT",
        semanticRole: "transaction_amount",
      },
      {
        kind: "fixed",
        text: " has been reversed. Ref# ",
      },
      {
        kind: "placeholder",
        token: "REFERENCE",
        semanticRole: "transaction_reference",
      },
      {
        kind: "fixed",
        text: ". For more details call ",
      },
      {
        kind: "placeholder",
        token: "PHONE",
        semanticRole: "provider_hotline",
      },
      {
        kind: "fixed",
        text: ".",
      },
    ],
    expectedOutcome: {
      kind: "transaction",
      direction: "income",
      reviewStatus: "needs_review",
      reviewReasons: ["low_confidence"],
      confidenceCeiling: 0.8,
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "f2306e984a4a097a16f6a0cd02e1dcd2f406d0a133898abf6b7ab529339d17a4",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-refund-card-usd-v1",
    patternVersion: 1,
    catalogVersion: 1,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "refund_or_reversal",
    currency: "USD",
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-refund-card-usd-v1",
    segments: [
      {
        kind: "fixed",
        text: "Your transaction with Debit Card **",
      },
      {
        kind: "placeholder",
        token: "LAST4",
        semanticRole: "card_last4",
      },
      {
        kind: "fixed",
        text: " @",
      },
      {
        kind: "placeholder",
        token: "MERCHANT",
        semanticRole: "merchant_name",
      },
      {
        kind: "fixed",
        text: " with ",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "fixed",
        text: " ",
      },
      {
        kind: "placeholder",
        token: "AMOUNT",
        semanticRole: "transaction_amount",
      },
      {
        kind: "fixed",
        text: " has been reversed",
      },
    ],
    expectedOutcome: {
      kind: "transaction",
      direction: "income",
      reviewStatus: "needs_review",
      reviewReasons: ["low_confidence"],
      confidenceCeiling: 0.8,
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "1055a8ca5c8c43b21ad8723824754261def21c6f12e7eac706d6535b4d7eb8eb",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-alahli-promotional-certificate-ar-v1",
    patternVersion: 1,
    catalogVersion: 1,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB ALAHLI"],
    messageFamily: "promotional",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-alahli-promotional-certificate-ar-v1",
    segments: [
      {
        kind: "fixed",
        text: "بنك QNB الأهلي يقدم اعلى عائد ثابت شهري ",
      },
      {
        kind: "placeholder",
        token: "PERCENTAGE",
        semanticRole: "promotional_rate",
      },
      {
        kind: "fixed",
        text: " و ربع سنوي ",
      },
      {
        kind: "placeholder",
        token: "PERCENTAGE",
        semanticRole: "promotional_rate",
      },
      {
        kind: "fixed",
        text: " على شهادات الادخار لمدة 3 سنوات و باقل حد ادنى ",
      },
      {
        kind: "placeholder",
        token: "AMOUNT",
        semanticRole: "promotional_amount",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "fixed",
        text: " و مضاعفاتها لربط الشهادة: ",
      },
      {
        kind: "placeholder",
        token: "URL",
        semanticRole: "public_url",
      },
      {
        kind: "fixed",
        text: " لمعرفة التفاصيل: ",
      },
      {
        kind: "placeholder",
        token: "URL",
        semanticRole: "public_url",
      },
      {
        kind: "fixed",
        text: " تطبق الشروط والأحكام رقم ت.ض: ",
      },
      {
        kind: "placeholder",
        token: "REFERENCE",
        semanticRole: "public_reference",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "promotional",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "fbc100dbab4d5623a72d0632ed5cb8a39d11cf7e8a40e9815ad73c7c9a84f5a1",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-informational-card-pickup-30d-ar-v1",
    patternVersion: 1,
    catalogVersion: 1,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "informational",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-informational-card-pickup-30d-ar-v1",
    segments: [
      {
        kind: "fixed",
        text: "عزيزى العميل نذكركم بضرورة استلام بطاقه الخصم المباشر حيث ستلغي بعد 30 يوم",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "informational",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "de46c125518051b07573c09e12f79e8f8904d0a55869a533d5366939c9e4e26a",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-alahli-promotional-bebasata-ar-v1",
    patternVersion: 1,
    catalogVersion: 1,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB ALAHLI"],
    messageFamily: "promotional",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-alahli-promotional-bebasata-ar-v1",
    segments: [
      {
        kind: "fixed",
        text: "حساب QNB bebasata بمزايا وعروض كتير اوى ! خطوات قليلة علشان تكمل إجراءات فتح حسابك مع QNB bebasata دوس هنا: ",
      },
      {
        kind: "placeholder",
        token: "URL",
        semanticRole: "public_url",
      },
      {
        kind: "fixed",
        text: " تطبق الشروط ت.ض ",
      },
      {
        kind: "placeholder",
        token: "REFERENCE",
        semanticRole: "public_reference",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "promotional",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "8dd3aea6baa67903c4f4cf30d45d54b49a0e9a0bcb8e6c3b610739a639b4f50d",
  },
] as const satisfies readonly TrustedSmsPattern[];
