import type { TrustedSmsPattern } from "../trusted-sms-pattern-types";

export const QNB_EGYPT_TRUSTED_SMS_PATTERNS_04 = [
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-informational-card-pickup-60d-ar-v1",
    patternVersion: 1,
    catalogVersion: 1,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "informational",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-informational-card-pickup-60d-ar-v1",
    segments: [
      {
        kind: "fixed",
        text: "عزيزي العميل، يرجي الحضور للفرع لاستلام بطاقه الخصم المباشر المصدرة حديثا حيث ستلغي بعد 60 يوم",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "informational",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "1a4ceca41f23aa6abc4cae01d81dfcd085cacf9e853dac64d898b6ca4ec8d41b",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-card-purchase-egp-v1",
    patternVersion: 1,
    catalogVersion: 1,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "card_purchase",
    currency: "EGP",
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-card-purchase-egp-v1",
    segments: [
      {
        kind: "fixed",
        text: "Your Debit Card **",
      },
      {
        kind: "placeholder",
        token: "LAST4",
        semanticRole: "card_last4",
      },
      {
        kind: "fixed",
        text: " had a Successful transaction of ",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "fixed",
        text: " ",
      },
      {
        kind: "placeholder",
        token: "AMOUNT",
        semanticRole: "transaction_amount",
      },
      {
        kind: "fixed",
        text: " @",
      },
      {
        kind: "placeholder",
        token: "MERCHANT",
        semanticRole: "merchant_name",
      },
      {
        kind: "fixed",
        text: ",your available bal.",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "fixed",
        text: " ",
      },
      {
        kind: "placeholder",
        token: "BALANCE",
        semanticRole: "available_balance",
      },
      {
        kind: "fixed",
        text: " for lost/stolen card call ",
      },
      {
        kind: "placeholder",
        token: "PHONE",
        semanticRole: "provider_hotline",
      },
    ],
    expectedOutcome: {
      kind: "transaction",
      direction: "expense",
      reviewStatus: "needs_review",
      reviewReasons: ["low_confidence"],
      confidenceCeiling: 0.8,
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "a16c4512021632414310905a46f7bb1385046c7387b45385a373e55ac54925fa",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-informational-phishing-warning-ar-v1",
    patternVersion: 1,
    catalogVersion: 1,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "informational",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-informational-phishing-warning-ar-v1",
    segments: [
      {
        kind: "fixed",
        text: "برجاء تجاهل وعدم الضغط على أي رابط في رسالة نصية خاصة بعروض او طلب معلومات مصرفية من جهة مجهولة حفاظا على حساباتكم البنكية حيث ان هذه الرسائل ليست صادرة من QNB مصر",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "informational",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "5fbc6cac5ac32fe822a4a8afa35cbed029d916fb69ea363b25e5268a30762610",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-informational-scam-warning-ar-v1",
    patternVersion: 1,
    catalogVersion: 1,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "informational",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-informational-scam-warning-ar-v1",
    segments: [
      {
        kind: "fixed",
        text: "يرجى العلم ان البنك لا يقدم أي هدايا عن طريق روابط غير موثوق بها كما يُحظر مشاركة البيانات الخاصة مع أي شخص. ت. ض:",
      },
      {
        kind: "placeholder",
        token: "PHONE",
        semanticRole: "provider_hotline",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "informational",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "0e6d80a82d3ff6f25ffa627adea04b449ed558dde3990bd521b3c4cd2ea5ef6c",
  },
] as const satisfies readonly TrustedSmsPattern[];
