import type { TrustedSmsPattern } from "../trusted-sms-pattern-types";

export const QNB_EGYPT_TRUSTED_SMS_PATTERNS_01 = [
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-outgoing-online-banking-transfer-egp-v1",
    patternVersion: 1,
    catalogVersion: 2,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "outgoing_bank_transfer",
    currency: "EGP",
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-outgoing-online-banking-transfer-egp-v1",
    segments: [
      {
        kind: "fixed",
        text: "You have requested a transfer of : ",
      },
      {
        kind: "placeholder",
        token: "AMOUNT",
        semanticRole: "transaction_amount",
      },
      {
        kind: "fixed",
        text: " ",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "fixed",
        text: " ,Please follow up on the transfer status through Online Banking",
      },
    ],
    expectedOutcome: {
      kind: "transaction",
      direction: "expense",
      reviewStatus: "needs_review",
      reviewReasons: ["low_confidence"],
      confidenceCeiling: 0.8,
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "2686fa9cc6852f558e82b285e1d6125a7278b5e203d90895cd47119f6bb6063a",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-refund-card-egp-v1",
    patternVersion: 1,
    catalogVersion: 2,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "refund_or_reversal",
    currency: "EGP",
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-refund-card-egp-v1",
    segments: [
      {
        kind: "fixed",
        text: "Your transaction with Debit Card **",
      },
      {
        kind: "placeholder",
        token: "LAST4",
        semanticRole: "card_last4",
      },
      {
        kind: "fixed",
        text: " @",
      },
      {
        kind: "placeholder",
        token: "MERCHANT",
        semanticRole: "merchant_name",
      },
      {
        kind: "fixed",
        text: " with ",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "fixed",
        text: " ",
      },
      {
        kind: "placeholder",
        token: "AMOUNT",
        semanticRole: "transaction_amount",
      },
      {
        kind: "fixed",
        text: " has been reversed",
      },
    ],
    expectedOutcome: {
      kind: "transaction",
      direction: "income",
      reviewStatus: "needs_review",
      reviewReasons: ["low_confidence"],
      confidenceCeiling: 0.8,
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "7d7bf0f95ca033034450567caa1d73c8ec0903b35c1b3ef66b452c692ff4b8be",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-refund-ipn-egp-v1",
    patternVersion: 1,
    catalogVersion: 2,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "refund_or_reversal",
    currency: "EGP",
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-refund-ipn-egp-v1",
    segments: [
      {
        kind: "fixed",
        text: "IPN transfer debited from ",
      },
      {
        kind: "placeholder",
        token: "ACCOUNT",
        semanticRole: "source_account_suffix",
      },
      {
        kind: "fixed",
        text: " with amount ",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "fixed",
        text: " ",
      },
      {
        kind: "placeholder",
        token: "AMOUNT",
        semanticRole: "transaction_amount",
      },
      {
        kind: "fixed",
        text: " has been reversed. Ref# ",
      },
      {
        kind: "placeholder",
        token: "REFERENCE",
        semanticRole: "transaction_reference",
      },
      {
        kind: "fixed",
        text: ". For more details call ",
      },
      {
        kind: "placeholder",
        token: "PHONE",
        semanticRole: "provider_hotline",
      },
      {
        kind: "fixed",
        text: ".",
      },
    ],
    expectedOutcome: {
      kind: "transaction",
      direction: "income",
      reviewStatus: "needs_review",
      reviewReasons: ["low_confidence"],
      confidenceCeiling: 0.8,
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "9ff76480a324f2fbdaf7e9048c0810532919c60b6c4547769d20e2259f769cb1",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-refund-card-usd-v1",
    patternVersion: 1,
    catalogVersion: 2,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "refund_or_reversal",
    currency: "USD",
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-refund-card-usd-v1",
    segments: [
      {
        kind: "fixed",
        text: "Your transaction with Debit Card **",
      },
      {
        kind: "placeholder",
        token: "LAST4",
        semanticRole: "card_last4",
      },
      {
        kind: "fixed",
        text: " @",
      },
      {
        kind: "placeholder",
        token: "MERCHANT",
        semanticRole: "merchant_name",
      },
      {
        kind: "fixed",
        text: " with ",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "fixed",
        text: " ",
      },
      {
        kind: "placeholder",
        token: "AMOUNT",
        semanticRole: "transaction_amount",
      },
      {
        kind: "fixed",
        text: " has been reversed",
      },
    ],
    expectedOutcome: {
      kind: "transaction",
      direction: "income",
      reviewStatus: "needs_review",
      reviewReasons: ["low_confidence"],
      confidenceCeiling: 0.8,
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "ba1689c8938c24de4c072fe4605771743cd23ed8ec7f9d52590d6e6fd7067954",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-alahli-promotional-certificate-ar-v1",
    patternVersion: 1,
    catalogVersion: 2,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB ALAHLI"],
    messageFamily: "promotional",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-alahli-promotional-certificate-ar-v1",
    segments: [
      {
        kind: "fixed",
        text: "بنك QNB الأهلي يقدم اعلى عائد ثابت شهري ",
      },
      {
        kind: "placeholder",
        token: "PERCENTAGE",
        semanticRole: "promotional_rate",
      },
      {
        kind: "fixed",
        text: " و ربع سنوي ",
      },
      {
        kind: "placeholder",
        token: "PERCENTAGE",
        semanticRole: "promotional_rate",
      },
      {
        kind: "fixed",
        text: " على شهادات الادخار لمدة 3 سنوات و باقل حد ادنى ",
      },
      {
        kind: "placeholder",
        token: "AMOUNT",
        semanticRole: "promotional_amount",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "fixed",
        text: " و مضاعفاتها لربط الشهادة: ",
      },
      {
        kind: "placeholder",
        token: "URL",
        semanticRole: "public_url",
      },
      {
        kind: "fixed",
        text: " لمعرفة التفاصيل: ",
      },
      {
        kind: "placeholder",
        token: "URL",
        semanticRole: "public_url",
      },
      {
        kind: "fixed",
        text: " تطبق الشروط والأحكام رقم ت.ض: ",
      },
      {
        kind: "placeholder",
        token: "REFERENCE",
        semanticRole: "public_reference",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "promotional",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "a1ec96e2cc8f00fe295ea9d18dbb758b7ea586f3ea2e26902a59fe4bf308a851",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-informational-card-pickup-30d-ar-v1",
    patternVersion: 1,
    catalogVersion: 2,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "informational",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-informational-card-pickup-30d-ar-v1",
    segments: [
      {
        kind: "fixed",
        text: "عزيزى العميل نذكركم بضرورة استلام بطاقه الخصم المباشر حيث ستلغي بعد 30 يوم",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "informational",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "35a3b458395a3ce8f0980d2ad8d14ee019e0b2465c6c721edd63a933f963a0cb",
  },
] as const satisfies readonly TrustedSmsPattern[];
