import type { TrustedSmsPattern } from "../trusted-sms-pattern-types";

export const QNB_EGYPT_TRUSTED_SMS_PATTERNS_04 = [
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-informational-card-pickup-45d-ar-v1",
    patternVersion: 1,
    catalogVersion: 2,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "informational",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-informational-card-pickup-45d-ar-v1",
    segments: [
      {
        kind: "fixed",
        text: "عزيزى العميل نذكركم بإستلام بطاقه الخصم المباشر حيث ستلغي بعد 45 يوم",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "informational",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "c65967c87609cf03214f7cae39867f1441c8acba08b5da9cd7ad979a563ac1e7",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-informational-card-pickup-60d-ar-v1",
    patternVersion: 1,
    catalogVersion: 2,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "informational",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-informational-card-pickup-60d-ar-v1",
    segments: [
      {
        kind: "fixed",
        text: "عزيزي العميل، يرجي الحضور للفرع لاستلام بطاقه الخصم المباشر المصدرة حديثا حيث ستلغي بعد 60 يوم",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "informational",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "a17c0e5d9a77c52c351cdf6da2cd9a634f1de7c37913adcf5966116835b00398",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-card-purchase-egp-v1",
    patternVersion: 1,
    catalogVersion: 2,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "card_purchase",
    currency: "EGP",
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-card-purchase-egp-v1",
    segments: [
      {
        kind: "fixed",
        text: "Your Debit Card **",
      },
      {
        kind: "placeholder",
        token: "LAST4",
        semanticRole: "card_last4",
      },
      {
        kind: "fixed",
        text: " had a Successful transaction of ",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "fixed",
        text: " ",
      },
      {
        kind: "placeholder",
        token: "AMOUNT",
        semanticRole: "transaction_amount",
      },
      {
        kind: "fixed",
        text: " @",
      },
      {
        kind: "placeholder",
        token: "MERCHANT",
        semanticRole: "merchant_name",
      },
      {
        kind: "fixed",
        text: ",your available bal.",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "placeholder",
        token: "BALANCE",
        semanticRole: "available_balance",
      },
      {
        kind: "fixed",
        text: " for lost/stolen card call ",
      },
      {
        kind: "placeholder",
        token: "PHONE",
        semanticRole: "provider_hotline",
      },
    ],
    expectedOutcome: {
      kind: "transaction",
      direction: "expense",
      reviewStatus: "needs_review",
      reviewReasons: ["low_confidence"],
      confidenceCeiling: 0.8,
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "fcf007a3f18974dd1eab1a3cf44a4a66399187e546cc295a1594d737b544b1a1",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-informational-phishing-warning-ar-v1",
    patternVersion: 1,
    catalogVersion: 2,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "informational",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-informational-phishing-warning-ar-v1",
    segments: [
      {
        kind: "fixed",
        text: "برجاء تجاهل وعدم الضغط على أي رابط في رسالة نصية خاصة بعروض او طلب معلومات مصرفية من جهة مجهولة حفاظا على حساباتكم البنكية حيث ان هذه الرسائل ليست صادرة من QNB مصر",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "informational",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "0c22c9dfe45e2b8b3c80a260cf622b19a20de523f694c4b9e3c796d788e7cae7",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-informational-scam-warning-ar-v1",
    patternVersion: 1,
    catalogVersion: 2,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "informational",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-informational-scam-warning-ar-v1",
    segments: [
      {
        kind: "fixed",
        text: "يرجى العلم ان البنك لا يقدم أي هدايا عن طريق روابط غير موثوق بها كما يُحظر مشاركة البيانات الخاصة مع أي شخص. ت. ض:",
      },
      {
        kind: "placeholder",
        token: "PHONE",
        semanticRole: "provider_hotline",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "informational",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "e5bcafee9632feff242e46fb89989fdec646c7c259cf14ce2e9d4234cb796df6",
  },
] as const satisfies readonly TrustedSmsPattern[];
