import type { TrustedSmsPattern } from "../trusted-sms-pattern-types";

export const QNB_EGYPT_TRUSTED_SMS_PATTERNS_03 = [
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-otp-card-purchase-v1",
    patternVersion: 1,
    catalogVersion: 1,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "otp",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-otp-card-purchase-v1",
    segments: [
      {
        kind: "fixed",
        text: "QNB OTP:",
      },
      {
        kind: "placeholder",
        token: "REFERENCE",
        semanticRole: "otp_code",
      },
      {
        kind: "fixed",
        text: " at ",
      },
      {
        kind: "placeholder",
        token: "MERCHANT",
        semanticRole: "merchant_name",
      },
      {
        kind: "fixed",
        text: " for ",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "fixed",
        text: " ",
      },
      {
        kind: "placeholder",
        token: "AMOUNT",
        semanticRole: "transaction_amount",
      },
      {
        kind: "fixed",
        text: " الرقم السرى مخصص لعملية الشراء اونلاين برجاء عدم الافصاح عنه",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "otp",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "20994936ff24c4a654436ed1c1b15c9dab0c7f08d91efb01ecbdc27c2013193c",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-atm-card-egp-v1",
    patternVersion: 1,
    catalogVersion: 1,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "atm_withdrawal",
    currency: "EGP",
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-atm-card-egp-v1",
    segments: [
      {
        kind: "fixed",
        text: "Your Debit Card **",
      },
      {
        kind: "placeholder",
        token: "LAST4",
        semanticRole: "card_last4",
      },
      {
        kind: "fixed",
        text: " had a Successful transaction of ",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "fixed",
        text: " ",
      },
      {
        kind: "placeholder",
        token: "AMOUNT",
        semanticRole: "transaction_amount",
      },
      {
        kind: "fixed",
        text: " @",
      },
      {
        kind: "placeholder",
        token: "ATM_TERMINAL",
        semanticRole: "atm_terminal",
      },
      {
        kind: "fixed",
        text: ",your available bal.",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "fixed",
        text: " ",
      },
      {
        kind: "placeholder",
        token: "BALANCE",
        semanticRole: "available_balance",
      },
      {
        kind: "fixed",
        text: " for lost/stolen card call ",
      },
      {
        kind: "placeholder",
        token: "PHONE",
        semanticRole: "provider_hotline",
      },
    ],
    expectedOutcome: {
      kind: "transaction",
      direction: "expense",
      reviewStatus: "needs_review",
      reviewReasons: ["low_confidence", "cash_transfer_review"],
      confidenceCeiling: 0.8,
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "78ca8c26b714862c65317eb383d0921566da25be380008f1afcd12bbd2ea5a33",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-atm-account-egp-v1",
    patternVersion: 1,
    catalogVersion: 1,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "atm_withdrawal",
    currency: "EGP",
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-atm-account-egp-v1",
    segments: [
      {
        kind: "fixed",
        text: "Dear Client, Amount of ",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "fixed",
        text: " ",
      },
      {
        kind: "placeholder",
        token: "AMOUNT",
        semanticRole: "transaction_amount",
      },
      {
        kind: "fixed",
        text: " was debited from your account for cash withdrawal based on your request. For more information, please call ",
      },
      {
        kind: "placeholder",
        token: "PHONE",
        semanticRole: "provider_hotline",
      },
    ],
    expectedOutcome: {
      kind: "transaction",
      direction: "expense",
      reviewStatus: "needs_review",
      reviewReasons: ["low_confidence", "cash_transfer_review"],
      confidenceCeiling: 0.8,
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "e74983fab7442b079445ab1c973bd4540ac6859310fcb822315dedeb84b2e4ec",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-incoming-ipn-egp-v1",
    patternVersion: 1,
    catalogVersion: 1,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "incoming_ipn_transfer",
    currency: "EGP",
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-incoming-ipn-egp-v1",
    segments: [
      {
        kind: "fixed",
        text: "IPN transfer received with amount of ",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "fixed",
        text: " ",
      },
      {
        kind: "placeholder",
        token: "AMOUNT",
        semanticRole: "transaction_amount",
      },
      {
        kind: "fixed",
        text: " on ",
      },
      {
        kind: "placeholder",
        token: "ACCOUNT",
        semanticRole: "source_account_suffix",
      },
      {
        kind: "fixed",
        text: " on ",
      },
      {
        kind: "placeholder",
        token: "DATE",
        semanticRole: "transaction_date",
      },
      {
        kind: "fixed",
        text: " at ",
      },
      {
        kind: "placeholder",
        token: "TIME",
        semanticRole: "transaction_time",
      },
      {
        kind: "fixed",
        text: ". Ref# ",
      },
      {
        kind: "placeholder",
        token: "REFERENCE",
        semanticRole: "transaction_reference",
      },
      {
        kind: "fixed",
        text: ". For more details call ",
      },
      {
        kind: "placeholder",
        token: "PHONE",
        semanticRole: "provider_hotline",
      },
      {
        kind: "fixed",
        text: ".",
      },
    ],
    expectedOutcome: {
      kind: "transaction",
      direction: "income",
      reviewStatus: "needs_review",
      reviewReasons: ["low_confidence"],
      confidenceCeiling: 0.8,
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "243465a3e86122edc0e73f905ebd65e0be29d14492aeab5793935c7eff195b03",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-outgoing-ipn-egp-v1",
    patternVersion: 1,
    catalogVersion: 1,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "outgoing_ipn_transfer",
    currency: "EGP",
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-outgoing-ipn-egp-v1",
    segments: [
      {
        kind: "fixed",
        text: "IPN transfer sent with amount of ",
      },
      {
        kind: "placeholder",
        token: "CURRENCY",
        semanticRole: "transaction_currency",
      },
      {
        kind: "fixed",
        text: " ",
      },
      {
        kind: "placeholder",
        token: "AMOUNT",
        semanticRole: "transaction_amount",
      },
      {
        kind: "fixed",
        text: " from ",
      },
      {
        kind: "placeholder",
        token: "ACCOUNT",
        semanticRole: "source_account_suffix",
      },
      {
        kind: "fixed",
        text: " on ",
      },
      {
        kind: "placeholder",
        token: "DATE",
        semanticRole: "transaction_date",
      },
      {
        kind: "fixed",
        text: " at ",
      },
      {
        kind: "placeholder",
        token: "TIME",
        semanticRole: "transaction_time",
      },
      {
        kind: "fixed",
        text: ". Ref# ",
      },
      {
        kind: "placeholder",
        token: "REFERENCE",
        semanticRole: "transaction_reference",
      },
      {
        kind: "fixed",
        text: ". For more details call ",
      },
      {
        kind: "placeholder",
        token: "PHONE",
        semanticRole: "provider_hotline",
      },
      {
        kind: "fixed",
        text: ".",
      },
    ],
    expectedOutcome: {
      kind: "transaction",
      direction: "expense",
      reviewStatus: "needs_review",
      reviewReasons: ["low_confidence"],
      confidenceCeiling: 0.8,
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "8b046c24f0179d87572cca3409eb150cfbc983e6217fb03d85f06b2c2d410d69",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-informational-card-pickup-45d-ar-v1",
    patternVersion: 1,
    catalogVersion: 1,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "informational",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-informational-card-pickup-45d-ar-v1",
    segments: [
      {
        kind: "fixed",
        text: "عزيزى العميل نذكركم بإستلام بطاقه الخصم المباشر حيث ستلغي بعد 45 يوم",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "informational",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "7207e8d694ce19a2f0e99a515b94276551502fe10702937fb3c6c23e125cdd24",
  },
] as const satisfies readonly TrustedSmsPattern[];
