import type { TrustedSmsPattern } from "../trusted-sms-pattern-types";

export const QNB_EGYPT_TRUSTED_SMS_PATTERNS_02 = [
  {
    schemaVersion: 1,
    patternId: "qnb-alahli-promotional-bebasata-ar-v1",
    patternVersion: 1,
    catalogVersion: 2,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB ALAHLI"],
    messageFamily: "promotional",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-alahli-promotional-bebasata-ar-v1",
    segments: [
      {
        kind: "fixed",
        text: "حساب QNB bebasata بمزايا وعروض كتير اوى ! خطوات قليلة علشان تكمل إجراءات فتح حسابك مع QNB bebasata دوس هنا: ",
      },
      {
        kind: "placeholder",
        token: "URL",
        semanticRole: "public_url",
      },
      {
        kind: "fixed",
        text: " تطبق الشروط ت.ض ",
      },
      {
        kind: "placeholder",
        token: "REFERENCE",
        semanticRole: "public_reference",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "promotional",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "75d1c4281b7a6bf08deb2ebcb6502ad6f158eb5d8944d1392590b84ba27bab87",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-alahli-otp-bebasata-v1",
    patternVersion: 1,
    catalogVersion: 2,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB ALAHLI"],
    messageFamily: "otp",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-alahli-otp-bebasata-v1",
    segments: [
      {
        kind: "fixed",
        text: "QNB Bebasata onetime password: ",
      },
      {
        kind: "placeholder",
        token: "REFERENCE",
        semanticRole: "otp_code",
      },
      {
        kind: "fixed",
        text: " , إدخل هذا الرقم بنفسك ولا تفصح عنه لأي شخص",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "otp",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "f556b5af915af2f8755f4ada4cf21b0badbad290b4d53146620cbcfa8a726ab9",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-alahli-informational-card-fee-refund-ar-v1",
    patternVersion: 1,
    catalogVersion: 2,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB ALAHLI"],
    messageFamily: "informational",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-alahli-informational-card-fee-refund-ar-v1",
    segments: [
      {
        kind: "fixed",
        text: "عميلنا العزيز ,من اليوم وحتي نهاية السنة سيتم رد مصاريف اصدار بطاقة QNBالأهلي الائتمانية الأساسية والتابعة مع اول استخدام تطبق الشروط ",
      },
      {
        kind: "placeholder",
        token: "URL",
        semanticRole: "public_url",
      },
      {
        kind: "fixed",
        text: " ت.ض ",
      },
      {
        kind: "placeholder",
        token: "REFERENCE",
        semanticRole: "public_reference",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "informational",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "b3c98f9c36494d0c58cda18d298495ecb9175e9165b58729e0621dd81e254d6e",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-alahli-informational-foreign-currency-ar-v1",
    patternVersion: 1,
    catalogVersion: 2,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB ALAHLI"],
    messageFamily: "informational",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-alahli-informational-foreign-currency-ar-v1",
    segments: [
      {
        kind: "fixed",
        text: "عميلنا العزيز، برجاء العلم ان معاملات الدفع بالعملات الأجنبية محلياً او دولياً على بطاقات الخصم المباشر المصدرة على حساباتكم بالجنيه المصري متوقفة حالياً، ويتم استخدام البطاقة بالجنيه المصري فقط تطبق الشروط ت ض ",
      },
      {
        kind: "placeholder",
        token: "REFERENCE",
        semanticRole: "public_reference",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "informational",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "01eee7858a49f30582b11f52459d1dd9a102ad9db1e8a2afb048b70717f18656",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-informational-fees-ar-v1",
    patternVersion: 1,
    catalogVersion: 2,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "informational",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-informational-fees-ar-v1",
    segments: [
      {
        kind: "fixed",
        text: "عميلنا العزيز، يرجي العلم بأنه تم تعديل المصاريف الخاصة بالخدمات والمنتجات المصرفية. لمزيد من المعلومات برجاء زيارة: ",
      },
      {
        kind: "placeholder",
        token: "URL",
        semanticRole: "public_url",
      },
      {
        kind: "fixed",
        text: " تطبق الشروط والاحكام ت.ض:",
      },
      {
        kind: "placeholder",
        token: "REFERENCE",
        semanticRole: "public_reference",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "informational",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "7d902d18784324821d340f5e040c2a398b3c366e6a59cd93a96709009d5dec07",
  },
  {
    schemaVersion: 1,
    patternId: "qnb-egypt-promotional-olympics-ar-v1",
    patternVersion: 1,
    catalogVersion: 2,
    providerId: "qnb-egypt",
    verifiedSenderAliases: ["QNB EGYPT"],
    messageFamily: "promotional",
    currency: null,
    enabled: true,
    runtimeScope: "trusted_production",
    sourceType: "qa-real-sms",
    autoSelectPolicy: "never",
    provenanceCode: "qa_operator_promoted",
    promotionId: "promotion-qnb-egypt-promotional-olympics-ar-v1",
    segments: [
      {
        kind: "fixed",
        text: "اصدر، فعل واستخدم بطاقاتQNB Visa الائتمانية خلال فاعليات الألعاب الأولمبية باريس ",
      },
      {
        kind: "placeholder",
        token: "DATE",
        semanticRole: "campaign_year",
      },
      {
        kind: "fixed",
        text: " وأحصل على نقاط ولاء إضافية تصل الي ",
      },
      {
        kind: "placeholder",
        token: "AMOUNT",
        semanticRole: "promotional_amount",
      },
      {
        kind: "fixed",
        text: " نقطة لطلب بطاقة ائتمانية:",
      },
      {
        kind: "placeholder",
        token: "URL",
        semanticRole: "public_url",
      },
      {
        kind: "fixed",
        text: " للمزيد:",
      },
      {
        kind: "placeholder",
        token: "URL",
        semanticRole: "public_url",
      },
      {
        kind: "fixed",
        text: " تطبق الشروط ت ض ",
      },
      {
        kind: "placeholder",
        token: "REFERENCE",
        semanticRole: "public_reference",
      },
    ],
    expectedOutcome: {
      kind: "rejection",
      reason: "promotional",
    },
    validationStatus: {
      schema: "passed",
      privacy: "passed",
      exactPositive: "passed",
      nearMatch: "passed",
      intentionalNegative: "passed",
      ambiguity: "passed",
      integrity: "passed",
    },
    integrityDigest:
      "6079ee722e966b7b0b05a21577c87a197a0775f81c8e77dc5aafbc1477fe675f",
  },
] as const satisfies readonly TrustedSmsPattern[];
