export const USER_DATA_ACCESS_ERROR_CODES = {
  USER_REQUIRED: "USER_REQUIRED",
  AUTH_SCOPE_CHANGED: "AUTH_SCOPE_CHANGED",
  OWNERSHIP_FAILED: "OWNERSHIP_FAILED",
  INVALID_PARENT_REFERENCE: "INVALID_PARENT_REFERENCE",
} as const;
